fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
        stages : [commit]
    -   id: end-of-file-fixer
        stages : [commit]
    -   id: trailing-whitespace
        stages : [commit]
    -   id: check-case-conflict
-   repo: local
    hooks:
    -   id: black
        stages: [push]
        exclude: .pre-commit-config.yaml | poetry.lock
        name: Black
        entry: poetry run black --diff --check .
        language: system
-   repo: local
    hooks:
    -   id: pylint
        stages: [push]
        name: Pylint
        entry: poetry run pylint ./dataacquisition/ && poetry run pylint ./tests/
        language: system
-   repo: local
    hooks:
    -   id: bandit
        stages: [push]
        name: Bandit
        entry: poetry run bandit -r ./dataacquisition/ && poetry run bandit -r ./tests/
        language: system
-   repo: local
    hooks:
    -   id: isort
        stages: [push]
        name: Isort
        entry: poetry run isort . -v -c
        language: system
-   repo: local
    hooks:
    -   id: safety
        stages: [push]
        name: Safety
        entry: poetry run safety check
        language: system
-   repo: local
    hooks:
    -   id: semgrep
        stages: [push]
        name: Semgrep
        entry: poetry run semgrep --config auto --error .
        language: system
