name: Dependency Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install poetry
        run: |
          pip install poetry
        
      - name: Install pylint
        run: |
          poetry install pylint
      
      - name: pylint
        run: |
          poetry run pylint ./dataacquisition/
          poetry run pylint ./tests/
          
      - name: Install bandit
        run: |
          poetry install bandit
          
      - name: bandit
        run: |
          poetry run bandit -r /dataacquisition/
          poetry run bandit -r /tests/
          
      - name: Install isort
        run: |
          poetry install isort
          
      - name: isort
        run: |
          poetry run isort . -v

      - name: Install safety
        run: |
          poetry install safety

      - name: safety
        run: |
          poetry run safety check
          
      - name: Install black
        run: |
          poetry install black
          
      - name: black
        run: |
          poetry run black --diff .
      
      - name: Install semgrep
        run: |
          poetry install semgrep
      
      - name: semgrep
        run: |
          poetry run semgrep --config auto .

